trigger:
- main
- dev/*
- rel/*

pr:
- main
- dev/*
- rel/*

pool:
  vmImage: windows-latest

variables:
  BuildConfiguration: Release

jobs:
- job: BuildBits
  displayName: Build and Test solution
  timeoutInMinutes: 60
  steps:

  # Set Build Version
  - script: nbgv cloud
    displayName: Set NBGV version

  # Verify headers
  - pwsh: build/Update-Headers.ps1 -Verify
    displayName: Verify headers

  # Restore solution
  - script: dotnet restore -p:Configuration=$(BuildConfiguration)
    displayName: Restore solution

  # Build solution
  - script: dotnet build --no-restore -c $(BuildConfiguration)
    displayName: Build solution

  # Test solution #

  # Run .NET 6 unit tests
  - script: dotnet test --no-build -c $(BuildConfiguration) -f net6.0 -l "trx;LogFileName=VSTestResults_net6.0.trx"
    displayName: Run .NET 6 unit tests

  # Run .NET Core 3.1 unit tests
  - script: dotnet test --no-build -c $(BuildConfiguration) -f netcoreapp3.1 -l "trx;LogFileName=VSTestResults_netcoreapp3.1.trx"
    displayName: Run .NET Core 3.1 unit tests

  # Run .NET Framework 4.7.2 unit tests
  - script: dotnet test --no-build -c $(BuildConfiguration) -f net472 -l "trx;LogFileName=VSTestResults_net472.trx"
    displayName: Run .NET Framework 4.7.2 unit tests

  # Publish test results
  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/TestResults/VSTestResults*.trx'
    condition: always()

  # Pack solution
  - script: dotnet pack --no-build -c $(BuildConfiguration)
    displayName: Pack solution

  # Sign packages
  - pwsh: build/Sign-Package.ps1
    displayName: Authenticode sign packages
    env:
      SignClientUser: $(SignClientUser)
      SignClientSecret: $(SignClientSecret)
      ArtifactDirectory: bin/nupkg
    condition: and(succeeded(), not(eq(variables['Build.Reason'], 'PullRequest')), not(eq(variables['SignClientSecret'], '')), not(eq(variables['SignClientUser'], '')))

  # Publish build artifacts
  - publish: bin/nupkg
    artifact: Packages
    displayName: Publish package artifacts
